# Generated by Django 5.2.6 on 2025-09-23 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sala', '0002_remove_sala_categoria_remove_sala_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPuntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(default=0)),
                ('fallos', models.IntegerField(default=0)),
                ('aciertos', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='sala.sala')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puntaje de Usuario',
                'verbose_name_plural': 'Puntajes de Usuarios',
                'unique_together': {('usuario', 'sala')},
            },
        ),
    ]
