# Generated by Django 5.2.6 on 2025-09-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioPuntaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopuntaje',
            name='nickname',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
